### ISSUE TITLE
Native retries cause delayed exceptions

### ISSUE THREAD

**Issue by Sleavely** [Sleavely/dynamo-plus#14]
**Problem**

Some exceptions such as `ExpiredTokenException` have `retryable` set to `true` but in reality it means credentials are unlikely to become invalid without additional user actions. 

For example, the following code using native AWS SDK:

```js
const DynamoDB = require('aws-sdk/clients/dynamodb')
const client= new DynamoDB .DocumentClient({region: 'eu-west-1'})
client.scan({TableName: 'some-table'}).promise()
```

Will yield the following error

```
ExpiredTokenException: The security token included in the request is expired
    at Request.extractError (C:\Git\sample-project\node_modules\aws-sdk\lib\protocol\json.js:51:27)
    at Request.callListeners (C:\Git\sample-project\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Git\sample-project\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Git\sample-project\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Git\sample-project\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Git\sample-project\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Git\sample-project\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Git\sample-project\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Git\sample-project\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Git\sample-project\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  message: 'The security token included in the request is expired',
  code: 'ExpiredTokenException',
  time: 2020-05-06T18:40:55.808Z,
  requestId: 'XXXTUTN8SITPXXX9HFGHEVL8AXXX4KQNSO5XXXVJF66Q9ASXXXJG',
  statusCode: 400,
  retryable: true
```

**Solution**

Setting [`maxRetries`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#maxRetries-property) to `0` when instantiating the DocumentClient will cause the AWS SDK to immediately abort, allowing Dynamo Plus to have full control of retries and backoffs, without postponing error propagation.

**Comment by Sleavely** [comment]
Removing "good first issue" label since the way forward isnt entirely clear (setting maxRetries to 0 contradicts #4). Input from the community would be appreciated.
