### ISSUE TITLE
Errors don't propagate to the caller correctly

### ISSUE THREAD

**Issue by Sleavely** [Sleavely/dynamo-plus#3]
When a non-retryable error occurs, it does not seem to propagate properly to the caller, resultign in an UnhandledPromiseRejection.

To reproduce, aim for a table that doesn't exist and enjoy the fireworks:

```js
const { DynamoPlus } = require('dynamo-plus')
const dynamoClient = DynamoPlus({ region: AWS_REGION })

console.log('Hello world!')

dynamoClient.scanAll({
  TableName: 'this-is-wack'
})
  .catch(err) => { console.error(`This line will never see the light of day :(`) })
  .then(() => { console.log(`I would love ending up here. I don't.`) })
```

Output:

```shell
> node myScript.js
Hello world!
(node:25596) UnhandledPromiseRejectionWarning: ResourceNotFoundException: Requested resource not found
    at Request.extractError (~/myProject/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (~/myProject/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (~/myProject/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (~/myProject/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (~/myProject/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (~/myProject/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at ~/myProject/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (~/myProject/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (~/myProject/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (~/myProject/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:25596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Sleavely** [comment]
Related: http://thecodebarbarian.com/async-await-error-handling-in-javascript.html
