### ISSUE TITLE
Support/Extend native retries?

### ISSUE THREAD

**Issue by Sleavely** [Sleavely/dynamo-plus#4]
The AWS JS SDK supports retries for retryable exceptions:

- Errors from the SDK has a "retryable" property, it could potentially be used to detect retryable errors. Does all of the error types covered by dynamo-plus set this property to `true`?
- There are two [options on the Dynamo constructor](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property) that have similar functionality to dynamo-plus'; `retryDelayOptions` and `maxRetries`

**Comment by Sleavely** [comment]
As an example, when hammering a table with millions of requests, there will be occassional errors like this one (which, I assume, has exceeded the default value of `maxRetries` already):

```json
{
        "message": "Internal server error",
        "code": "InternalServerError",
        "time": {},
        "requestId": "BQR4BOD8NMEK2JRVKVUR3F6LR7VV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 500,
        "retryable": true,
        "name": "InternalServerError",
        "stack": "InternalServerError: Internal server error\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    }
```

**Comment by Sleavely** [comment]
It's worth noting that #14 would mean we rely less on the native retries in order to have full control over which errors are considered retryable.
